name: Build & Send APK to Telegram
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
      - run: flutter create .
      - run: flutter build apk --debug
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/app-debug.apk
          message: "🚀 لعبة شطر - بناء جديد!"
